EMSNAME = GripAndShoot

COMMON = ../CommonZeta/eap
SCHEMA = ../../Schema/GripAndShootSchema

OBJECTS = main.obj busywait.obj hal.obj hal_power.obj hal_timer.obj hal_uart.obj $(EMSNAME).obj

include $(COMMON)/rules.mk
